apiVersion: v1
kind: Pod
metadata:
  name: busybox-load
  namespace: apache
  labels:
    app: load-test
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "Starting load test..."
          while true; do
            wget -q -O- http://apache-service.apache.svc.cluster.local
          done
